---
- name: Ensure Yum/DNF Neo4j repository exists
  template:
    src: files/neo4j.repo
    dest: /etc/yum.repos.d/neo4j.repo

- name: Ensure Neo Technology GPG key is imported
  rpm_key:
    key: https://debian.neo4j.com/neotechnology.gpg.key

- name: Set specific stable version to install
  set_fact:
    neo4j_package_name: "neo4j-{{ neo4j_version }}"
  when: neo4j_version is defined

- name: Ensure Neo4j packages are installed
  dnf:
    name: "{{ neo4j_package_name | default(_neo4j_package_name) }}"
    state: present

- name: Ensure service is started and enabled
  service:
    name: neo4j
    state: started
    enabled: true

- name: Set listening address
  lineinfile:
    path: /etc/neo4j/neo4j.conf
    regexp: '^#dbms.default_listen_address='
    line: "dbms.default_listen_address={{ neo4j_listen_address }}"
  when: neo4j_listen_address is defined
  notify: restart neo4j server
