---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/geerlingguy/docker-centos8-ansible:latest
    pre_build_image: true
    network_mode: host
provisioner:
  name: ansible
verifier:
  name: ansible
